openapi: 3.0.2
info:
  description: Tilgjengeliggjør api-beskrivelser fra en api-katalog ihht DCAT-AP-NO v2.0
  version: '1.0'
  title: FDK sin API-katalog
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: dcat-ap-no-catalogs
    description: DCAT-AP-NO catalogs
  - name: dcat-ap-no-dataservices
    description: DCAT-AP-NO dataservices
servers:
  - url: 'https://dcat-ap-no.fellesdatakatalog.brreg.no/'
    description: Produksjonsversjon
  - url: 'https://dcat-ap-no.ut1.fellesdatakatalog.brreg.no/'
    description: utviklingsversjon av API server
paths:
  /catalogs:
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returnerer samlinger av kataloger
      operationId: getCatalogs
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: object
            application/rdf+json:
              schema:
                type: object
            application/ld+json:
              schema:
                type: object
            application/rdf+xml:
              schema:
                type: object
  /dataservices:
    get:
      tags:
        - dcat-ap-no-dataservices
      description: Returnerer samlinger av dataservicer
      operationId: getDataServices
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: object
            application/rdf+json:
              schema:
                type: object
            application/ld+json:
              schema:
                type: object
            application/rdf+xml:
              schema:
                type: object
