logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}

spring:
  data:
    mongodb:
      authentication-database: admin
      database: dataservice-catalog
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: mongodb
      port: 27017
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    template:
      routing-key: 'dataservice.publisher.HarvestTrigger'
      exchange: 'harvests'

security:
  jwks-uri: ${SSO_HOST}/auth/realms/fdk/protocol/openid-connect/certs

application:
  data-service-catalog-gui-url: ${DATA_SERVICE_CATALOG_GUI_URL}
  catalog-base-uri: ${CATALOG_BASE_URI:http://localhost}
  external:
    api-harvester:
      url: http://fdk-nginx-search:8080/api
---

security:
  jwks-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs

spring:
  profiles: develop,test,unit-integration

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    template:
      routing-key: 'dataservice.publisher.HarvestTrigger'
      exchange: 'harvests'
  data:
    mongodb:
      authentication-database: admin
      database: dataservice-catalog
      username: admin
      password: admin
      host: localhost
      port: 27017
server:
  port: 9080

application:
  data-service-catalog-gui-url: http://localhost:8141
  external:
    api-harvester:
      url: http://localhost:8103