logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: INFO
  level.org.springframework.web: INFO
  level.org.springframework.data.elasticsearch.core: ${LOG_LEVEL:INFO}
  level.org.opensaml: INFO
application:
  harvesterUsername: ${registrationApi_harvesterUsername:test_admin}
  harvesterPassword: ${registrationApi_harvesterPassword:password}
  apiRootUrl: http://nginx-search:8080/api
  # harvest every sixth hour
  harvestCron: 0 0 */6 * * *

spring:
  jackson:
    default-property-inclusion: non_null
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

security:
  oauth2:
    resource:
      id: fdk-registration-api
      jwk.key-set-uri: http://sso:8084/auth/realms/fdk/protocol/openid-connect/certs

---
spring:
  profiles: develop
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
server:
  port: 8115
application:
  harvesterUrl: http://localhost:8082
  apiRootUrl: http://localhost:8080/api

security:
  oauth2:
    resource:
      jwk.key-set-uri: http://localhost:8084/auth/realms/fdk/protocol/openid-connect/certs
---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9399
      clusterName: elasticsearch
      properties:
        http:
          enabled: true

